// ── CDN ──
const CDN_RAW = "https://github.com/dudwp1221-byte/pokeset-images";
function cleanCDN(u) {
  u = u
    .trim()
    .replace(/\/$/, "")
    .replace(/\.git$/, "");
  u = u.replace(
    /^https?:\/\/github\.com\/([^/]+)\/([^/]+)(\/.*)?$/,
    (_, a, b, r) =>
      `https://raw.githubusercontent.com/${a}/${b}/${
        r ? r.replace(/^\//, "") : "main"
      }`
  );
  if (u.includes("raw.githubusercontent.com")) {
    const p = u.replace("https://raw.githubusercontent.com/", "").split("/");
    if (p.length < 3) u += "/main";
  }
  return u;
}
export const CLEAN = cleanCDN(CDN_RAW);

// ── 덱 타입 ──
export const TYPES = ["A", "B", "C"];
export const SD_DEFAULT = 20;

// ── 속성 그룹 ──
export const GROUPS = [
  {
    id: "electric",
    label: "전기",
    emoji: "⚡",
    color: "#F7D02C",
    bg: "#FFF9C4",
  },
  { id: "water", label: "물", emoji: "💧", color: "#6390F0", bg: "#E3EAFD" },
  { id: "grass", label: "풀", emoji: "🌿", color: "#7AC74C", bg: "#E8F5E9" },
  { id: "poison", label: "독", emoji: "☠", color: "#A33EA1", bg: "#F3E5F5" },
  { id: "ground", label: "땅", emoji: "🌍", color: "#C8A850", bg: "#FFF8E1" },
  { id: "fire", label: "불", emoji: "🔥", color: "#EE8130", bg: "#FFF3E0" },
  { id: "normal", label: "노말", emoji: "★", color: "#A0A0A0", bg: "#F5F5F5" },
  { id: "rock", label: "바위", emoji: "🗿", color: "#5C4A1E", bg: "#F3F4F6" },
];

export const JOHTO_GROUPS = [
  {
    id: "electric",
    label: "전기",
    emoji: "⚡",
    color: "#F7D02C",
    bg: "#FFF9C4",
  },
  { id: "water", label: "물", emoji: "💧", color: "#6390F0", bg: "#E3EAFD" },
  { id: "grass", label: "풀", emoji: "🌿", color: "#7AC74C", bg: "#E8F5E9" },
  { id: "dark", label: "악", emoji: "🌑", color: "#1E2D6B", bg: "#EDEDF5" },
  {
    id: "fairy",
    label: "페어리",
    emoji: "🌸",
    color: "#EC8FE6",
    bg: "#FDF4FF",
  },
  { id: "fire", label: "불", emoji: "🔥", color: "#EE8130", bg: "#FFF3E0" },
  { id: "normal", label: "노말", emoji: "★", color: "#A0A0A0", bg: "#F5F5F5" },
  {
    id: "psychic",
    label: "에스퍼",
    emoji: "🔮",
    color: "#C2185B",
    bg: "#FFF0F5",
  },
];

export const HOENN_GROUPS = [
  {
    id: "electric",
    label: "전기",
    emoji: "⚡",
    color: "#F7D02C",
    bg: "#FFF9C4",
  },
  { id: "water", label: "물", emoji: "💧", color: "#6390F0", bg: "#E3EAFD" },
  { id: "grass", label: "풀", emoji: "🌿", color: "#7AC74C", bg: "#E8F5E9" },
  { id: "ice", label: "얼음", emoji: "🧊", color: "#2196A0", bg: "#E8F8F8" },
  { id: "bug", label: "벌레", emoji: "🐛", color: "#A6B91A", bg: "#F4F8E0" },
  { id: "fire", label: "불", emoji: "🔥", color: "#EE8130", bg: "#FFF3E0" },
  { id: "normal", label: "노말", emoji: "★", color: "#A0A0A0", bg: "#F5F5F5" },
  {
    id: "psychic",
    label: "에스퍼",
    emoji: "🔮",
    color: "#C2185B",
    bg: "#FFF0F5",
  },
];

export const GMAP = {
  ...Object.fromEntries(GROUPS.map((g) => [g.id, g])),
  ...Object.fromEntries(JOHTO_GROUPS.map((g) => [g.id, g])),
  ...Object.fromEntries(HOENN_GROUPS.map((g) => [g.id, g])),
};

// ── 카드 파일명 맵 ──
export const KANTO_MAP = {
  electric_A: "A_전기A",
  electric_B: "A_전기B",
  electric_C: "A_전기C",
  water_A: "B_물A",
  water_B: "B_물B",
  water_C: "B_물C",
  grass_A: "C_풀A",
  grass_B: "C_풀B",
  grass_C: "C_풀C",
  poison_A: "D_독A",
  poison_B: "D_독B",
  poison_C: "D_독C",
  ground_A: "E_땅A",
  ground_B: "E_땅B",
  ground_C: "E_땅C",
  fire_A: "F_불A",
  fire_B: "F_불B",
  fire_C: "F_불C",
  normal_A: "G_노말A",
  normal_B: "G_노말B",
  normal_C: "G_노말C",
  rock_A: "H_바위A",
  rock_B: "H_바위B",
  rock_C: "H_바위C",
  joker_1: "I_조커1",
  joker_2: "I_조커2",
};

export const JOHTO_MAP = {
  electric_A: "A_전기A",
  electric_B: "A_전기B",
  electric_C: "A_전기C",
  water_A: "B_물A",
  water_B: "B_물B",
  water_C: "B_물C",
  grass_A: "C_풀A",
  grass_B: "C_풀B",
  grass_C: "C_풀C",
  dark_A: "D_악A",
  dark_B: "D_악B",
  dark_C: "D_악C",
  fairy_A: "E_페어리A",
  fairy_B: "E_페어리B",
  fairy_C: "E_페어리C",
  fire_A: "F_불A",
  fire_B: "F_불B",
  fire_C: "F_불C",
  normal_A: "G_노말A",
  normal_B: "G_노말B",
  normal_C: "G_노말C",
  psychic_A: "H_에스퍼A",
  psychic_B: "H_에스퍼B",
  psychic_C: "H_에스퍼C",
  joker_1: "I_조커1",
  joker_2: "I_조커2",
};

export const HOENN_MAP = {
  electric_A: "A_전기A",
  electric_B: "A_전기B",
  electric_C: "A_전기C",
  water_A: "B_물A",
  water_B: "B_물B",
  water_C: "B_물C",
  grass_A: "C_풀A",
  grass_B: "C_풀B",
  grass_C: "C_풀C",
  ice_A: "D_얼음A",
  ice_B: "D_얼음B",
  ice_C: "D_얼음C",
  bug_A: "E_벌레A",
  bug_B: "E_벌레B",
  bug_C: "E_벌레C",
  fire_A: "F_불A",
  fire_B: "F_불B",
  fire_C: "F_불C",
  normal_A: "G_노말A",
  normal_B: "G_노말B",
  normal_C: "G_노말C",
  psychic_A: "H_에스퍼A",
  psychic_B: "H_에스퍼B",
  psychic_C: "H_에스퍼C",
  joker_1: "I_조커1",
  joker_2: "I_조커2",
};

// ── 리그 정의 ──
export const LEAGUES = [
  {
    id: "kanto",
    name: "관동 지방",
    emoji: "⚡",
    badge: "🏅",
    color: "#6366F1",
    bg: "#EEF2FF",
    border: "#C7D2FE",
    bet: 30,
    sdAmount: 60,
    minCoins: 0,
    desc: "입문자 리그 · 낮은 배팅금",
    cardPrefix: null,
    fileMap: null,
    groups: GROUPS,
  },
  {
    id: "johto",
    name: "성도 지방",
    emoji: "🌿",
    badge: "🥈",
    color: "#10B981",
    bg: "#ECFDF5",
    border: "#A7F3D0",
    bet: 80,
    sdAmount: 160,
    minCoins: 500,
    desc: "중급자 리그 · 중간 배팅금",
    cardPrefix: "johto",
    fileMap: JOHTO_MAP,
    groups: JOHTO_GROUPS,
  },
  {
    id: "hoenn",
    name: "호연 지방",
    emoji: "🌊",
    badge: "🏆",
    color: "#F59E0B",
    bg: "#FFFBEB",
    border: "#FDE68A",
    bet: 150,
    sdAmount: 300,
    minCoins: 1200,
    desc: "상급자 리그 · 높은 배팅금",
    cardPrefix: "hoenn",
    fileMap: HOENN_MAP,
    groups: HOENN_GROUPS,
  },
];

// ── 시작 코인 ──
export const START_COINS = 500;

// ── 상점 아이템 ──
export const SHOP_ITEMS = [
  // ── 기타 ──────────────────────────────────────────────
  {
    id: "card_back_2",
    name: "레드 카드백",
    type: "card_back",
    price: 100,
    file: "shop_card_back_2",
    emoji: "🔴",
    desc: "빨간 테마 뒷면",
  },
  {
    id: "lobby_bg_2",
    name: "로비 배경 2",
    type: "lobby_bg",
    price: 150,
    file: "shop_lobby_bg_2",
    emoji: "🌆",
    desc: "도시 야경",
  },
  {
    id: "game_bg_2",
    name: "인게임 배경 2",
    type: "game_bg",
    price: 150,
    file: "shop_game_bg_2",
    emoji: "🌃",
    desc: "야간 경기장",
  },
  {
    id: "bgm_2",
    name: "BGM 2",
    type: "bgm",
    price: 200,
    file: "shop_bgm_2",
    emoji: "🎶",
    desc: "배틀 BGM",
  },

  // ── 이모트 — 정지 (png/jpg) · 500코인 ────────────────
  {
    id: "emote_arrogant",
    name: "거만",
    type: "emote",
    price: 500,
    file: "emote_arrogant",
    emoji: "😤",
    desc: "거만",
  },
  {
    id: "emote_sneer",
    name: "비웃음",
    type: "emote",
    price: 500,
    file: "emote_sneer",
    emoji: "🙄",
    desc: "비웃음",
  },
  {
    id: "emote_tease",
    name: "놀리기",
    type: "emote",
    price: 500,
    file: "emote_tease",
    emoji: "😝",
    desc: "놀리기",
  },
  {
    id: "emote_tears",
    name: "눈물",
    type: "emote",
    price: 500,
    file: "emote_tears",
    emoji: "😢",
    desc: "눈물",
  },
  {
    id: "emote_upset",
    name: "언짢은",
    type: "emote",
    price: 500,
    file: "emote_upset",
    emoji: "😠",
    desc: "언짢음",
  },

  // ── 이모트 — 움직이는 (gif/mp4) · 1000코인 ───────────
  {
    id: "emote_smile",
    name: "미소",
    type: "emote",
    price: 1000,
    file: "emote_smile",
    emoji: "😊",
    desc: "미소",
  },
  {
    id: "emote_sob",
    name: "오열",
    type: "emote",
    price: 1000,
    file: "emote_sob",
    emoji: "😭",
    desc: "흑흑",
  },
  {
    id: "emote_tongue",
    name: "메롱",
    type: "emote",
    price: 1000,
    file: "emote_tongue",
    emoji: "😛",
    desc: "메롱",
  },
  {
    id: "emote_melong",
    name: "메롱2",
    type: "emote",
    price: 1000,
    file: "emote_melong",
    emoji: "👅",
    desc: "메롱2",
  },
  {
    id: "emote_question",
    name: "물음표",
    type: "emote",
    price: 1000,
    file: "emote_question",
    emoji: "❓",
    desc: "물음표",
  },
  {
    id: "emote_kick",
    name: "발차기",
    type: "emote",
    price: 1000,
    file: "emote_kick",
    emoji: "🦵",
    desc: "발차기",
  },
  {
    id: "emote_slap",
    name: "뺨때리기",
    type: "emote",
    price: 1000,
    file: "emote_slap",
    emoji: "👊",
    desc: "철썩",
  },
  {
    id: "emote_swirl",
    name: "소용돌이",
    type: "emote",
    price: 1000,
    file: "emote_swirl",
    emoji: "🌀",
    desc: "소용돌이",
  },
  {
    id: "emote_slapcombo",
    name: "연속공격",
    type: "emote",
    price: 1000,
    file: "emote_slapcombo",
    emoji: "💢",
    desc: "연속공격",
  },
  {
    id: "emote_slapcombo2",
    name: "연속공격2",
    type: "emote",
    price: 1000,
    file: "emote_slapcombo2",
    emoji: "💥",
    desc: "연속공격2",
  },
];

// ── 트레이너 풀 ──
export const TRAINER_POOL = [
  { n: "강연", e: "⚙" },
  { n: "국화", e: "🐉" },
  { n: "규리", e: "🥊" },
  { n: "그린", e: "🍃" },
  { n: "꼭두", e: "🔬" },
  { n: "난천", e: "🐲" },
  { n: "네모", e: "⭐" },
  { n: "노간주", e: "🌿" },
  { n: "단델", e: "🏆" },
  { n: "도희", e: "🌺" },
  { n: "독수", e: "☠" },
  { n: "류옹", e: "🪨" },
  { n: "마티스", e: "⚡" },
  { n: "목호", e: "👻" },
  { n: "미월", e: "🌙" },
  { n: "민화", e: "🌸" },
  { n: "비상", e: "🦋" },
  { n: "비주기", e: "🔮" },
  { n: "사도", e: "🦴" },
  { n: "성호", e: "⚔" },
  { n: "시바", e: "👊" },
  { n: "아이리스", e: "🐉" },
  { n: "영태", e: "🌊" },
  { n: "웅", e: "🪨" },
  { n: "유빈", e: "💫" },
  { n: "윤진", e: "🌟" },
  { n: "이슬", e: "💧" },
  { n: "이향", e: "🌺" },
  { n: "일목", e: "🌲" },
  { n: "진우", e: "⚡" },
  { n: "초련", e: "🔥" },
  { n: "카렌", e: "🌑" },
  { n: "카르네", e: "🌹" },
  { n: "카지", e: "🌊" },
  { n: "칸나", e: "❄" },
  { n: "테사", e: "⭐" },
  { n: "공명", e: "🎭" },
  { n: "광휘", e: "🌪" },
  { n: "금선", e: "✨" },
  { n: "레드", e: "🏔" },
  { n: "리프", e: "🌿" },
  { n: "명희", e: "🌸" },
  { n: "봄이", e: "🌸" },
  { n: "빛나", e: "⭐" },
  { n: "심향", e: "🌙" },
  { n: "투지", e: "🔮" },
  { n: "투희", e: "💜" },
  { n: "칼름", e: "🌿" },
  { n: "세레나", e: "🌹" },
  { n: "공박사", e: "🔭" },
  { n: "오박사", e: "🔬" },
  { n: "로이", e: "🗡" },
  { n: "로사", e: "🌸" },
  { n: "마박사", e: "🌺" },
  { n: "주박사", e: "🌿" },
  { n: "털보박사", e: "🧔" },
  { n: "지우", e: "⭐" },
];

export const TOP_CROP = new Set([
  "공명",
  "광휘",
  "금선",
  "레드",
  "리프",
  "명희",
  "봄이",
  "빛나",
  "심향",
  "투지",
  "투희",
  "칼름",
  "세레나",
  "공박사",
  "오박사",
  "로이",
  "로사",
  "마박사",
  "주박사",
  "털보박사",
  "지우",
]);

export const T = {
  강연: [
    "#485868",
    "#687888",
    "#F0F0F8",
    "#C8D0D8",
    "twintails",
    "gentle",
    "#485868",
    null,
  ],
  국화: [
    "#100848",
    "#180868",
    "#FAD0A8",
    "#C81010",
    "tall",
    "sharp",
    "#181818",
    "cape",
  ],
  규리: [
    "#C04858",
    "#D85870",
    "#FAD0A8",
    "#E8C000",
    "top",
    "normal",
    "#C04858",
    null,
  ],
  그린: [
    "#106020",
    "#C02020",
    "#FAD0A8",
    "#604010",
    "top",
    "normal",
    "#2060A0",
    "hat",
  ],
  꼭두: [
    "#183870",
    "#204898",
    "#F0F8FF",
    "#3878D8",
    "tall",
    "glasses",
    "#183870",
    null,
  ],
  난천: [
    "#1848A8",
    "#2060C8",
    "#FAD0A8",
    "#2860D8",
    "long",
    "sharp",
    "#1848A8",
    null,
  ],
  네모: [
    "#184888",
    "#E87028",
    "#FAD0A8",
    "#2870D8",
    "top",
    "normal",
    "#184888",
    null,
  ],
  노간주: [
    "#5A6840",
    "#F0F0E8",
    "#FAD0A8",
    "#8B5A14",
    "top",
    "glasses",
    "#5A6840",
    null,
  ],
  단델: [
    "#480878",
    "#580888",
    "#FAD0A8",
    "#8820D8",
    "long",
    "normal",
    "#202840",
    "cape",
  ],
  도희: [
    "#C84070",
    "#D85080",
    "#F8D0A0",
    "#C03870",
    "ponytailR",
    "gentle",
    "#C03870",
    null,
  ],
  독수: [
    "#3A0A58",
    "#180830",
    "#C8C0A0",
    "#1A1A1A",
    "top",
    "narrow",
    "#1A1A1A",
    "mask",
  ],
  류옹: [
    "#504830",
    "#383020",
    "#C89060",
    "#707060",
    "top",
    "old",
    "#303020",
    null,
  ],
  마티스: [
    "#3A6018",
    "#4A7828",
    "#FAD0A8",
    "#D8C000",
    "tall",
    "intense",
    "#2858A0",
    null,
  ],
  목호: [
    "#200830",
    "#301848",
    "#D0B8A8",
    "#F0F0E8",
    "curly",
    "old",
    "#282840",
    null,
  ],
  미월: [
    "#382870",
    "#482888",
    "#F0E8F8",
    "#D0B0F0",
    "long",
    "gentle",
    "#382870",
    null,
  ],
  민화: [
    "#C83020",
    "#D84030",
    "#FAD0A8",
    "#D02810",
    "tall",
    "normal",
    "#202840",
    null,
  ],
  비상: [
    "#1A6848",
    "#287858",
    "#FAD0A8",
    "#18A868",
    "ponytailR",
    "normal",
    "#185838",
    null,
  ],
  비주기: [
    "#380848",
    "#280438",
    "#F0F0F8",
    "#1A1A1A",
    "long",
    "narrow",
    "#6010A0",
    null,
  ],
  사도: [
    "#402010",
    "#583020",
    "#C89860",
    "#3A2010",
    "long",
    "sharp",
    "#402010",
    null,
  ],
  성호: [
    "#203060",
    "#283870",
    "#FAD0A8",
    "#204888",
    "top",
    "normal",
    "#203060",
    null,
  ],
  시바: [
    "#200808",
    "#06080C",
    "#280A04",
    "#181818",
    "top",
    "intense",
    "#181818",
    null,
  ],
  아이리스: [
    "#281848",
    "#382858",
    "#5A3010",
    "#181818",
    "twintails",
    "normal",
    "#481878",
    null,
  ],
  영태: [
    "#184838",
    "#285848",
    "#FAD0A8",
    "#184838",
    "top",
    "normal",
    "#184838",
    null,
  ],
  웅: [
    "#4A2810",
    "#6B8B20",
    "#B87838",
    "#1A1A1A",
    "top",
    "shut",
    "#1A1A1A",
    null,
  ],
  유빈: [
    "#C03878",
    "#D04888",
    "#FAD0A8",
    "#C02868",
    "ponytailR",
    "gentle",
    "#C03878",
    null,
  ],
  윤진: [
    "#183860",
    "#284870",
    "#FAD0A8",
    "#183860",
    "top",
    "normal",
    "#183860",
    null,
  ],
  이슬: [
    "#0E5A9A",
    "#00A8A8",
    "#FAD0A8",
    "#E85000",
    "ponytailR",
    "normal",
    "#2090D0",
    null,
  ],
  이향: [
    "#384878",
    "#485888",
    "#FAD0A8",
    "#2838A8",
    "long",
    "gentle",
    "#384878",
    null,
  ],
  일목: [
    "#304828",
    "#405838",
    "#FAD0A8",
    "#184828",
    "top",
    "normal",
    "#304828",
    null,
  ],
  진우: [
    "#483018",
    "#584028",
    "#FAD0A8",
    "#483018",
    "top",
    "normal",
    "#483018",
    null,
  ],
  초련: [
    "#A81808",
    "#781008",
    "#F0C898",
    "#F0F0F0",
    "bald",
    "normal",
    "#283040",
    "moustache",
  ],
  카렌: [
    "#181820",
    "#080810",
    "#E8E8F8",
    "#1A1A1A",
    "long",
    "smug",
    "#181818",
    null,
  ],
  카르네: [
    "#C82848",
    "#D83858",
    "#FAD0A8",
    "#C82848",
    "ponytailR",
    "gentle",
    "#C82848",
    null,
  ],
  카지: [
    "#286840",
    "#388850",
    "#F0D8A8",
    "#1A3820",
    "top",
    "normal",
    "#286840",
    null,
  ],
  칸나: [
    "#0A2860",
    "#102870",
    "#FAD0A8",
    "#A02018",
    "long",
    "glasses",
    "#0A2860",
    null,
  ],
  테사: [
    "#485060",
    "#586070",
    "#FAE8D8",
    "#B8B0A8",
    "top",
    "gentle",
    "#485060",
    null,
  ],
  공명: [
    "#284870",
    "#384880",
    "#FAD0A8",
    "#8888B8",
    "top",
    "kind",
    "#284870",
    null,
  ],
  광휘: [
    "#281810",
    "#181010",
    "#5A3010",
    "#1A1A1A",
    "tall",
    "smug",
    "#281810",
    null,
  ],
  금선: [
    "#785820",
    "#886830",
    "#F8D0A0",
    "#C8A820",
    "ponytailR",
    "gentle",
    "#785820",
    null,
  ],
  레드: [
    "#980000",
    "#780000",
    "#FAD0A8",
    "#181818",
    "cap",
    "det",
    "#202840",
    null,
  ],
  리프: [
    "#186828",
    "#C02020",
    "#FAD0A8",
    "#604010",
    "top",
    "normal",
    "#2060A0",
    "hat",
  ],
  명희: [
    "#A83858",
    "#B84868",
    "#FAD0A8",
    "#A03858",
    "ponytailR",
    "gentle",
    "#A03858",
    null,
  ],
  봄이: [
    "#C86028",
    "#D87038",
    "#FAD0A8",
    "#C83018",
    "ponytailR",
    "normal",
    "#C06028",
    null,
  ],
  빛나: [
    "#183888",
    "#E8F0F8",
    "#FAD0A8",
    "#2838C8",
    "top",
    "normal",
    "#183888",
    "hat",
  ],
  심향: [
    "#382050",
    "#482860",
    "#F0E8F8",
    "#A878D8",
    "long",
    "narrow",
    "#382050",
    null,
  ],
  투지: [
    "#1A1030",
    "#2A2040",
    "#FAD0A8",
    "#6858A8",
    "tall",
    "sharp",
    "#1A1030",
    "cape",
  ],
  투희: [
    "#381040",
    "#481850",
    "#FAD0A8",
    "#7848C8",
    "long",
    "gentle",
    "#381040",
    null,
  ],
  칼름: [
    "#184828",
    "#285838",
    "#FAD0A8",
    "#183828",
    "top",
    "det",
    "#184828",
    null,
  ],
  세레나: [
    "#483818",
    "#C84828",
    "#FAD0A8",
    "#B87828",
    "long",
    "gentle",
    "#483818",
    "hat",
  ],
  공박사: [
    "#246024",
    "#F0F0E8",
    "#FAD0A8",
    "#704010",
    "top",
    "glasses",
    "#246024",
    null,
  ],
  오박사: [
    "#6A6038",
    "#F0F0E8",
    "#F0C898",
    "#909090",
    "top",
    "kind",
    "#505870",
    null,
  ],
  로이: [
    "#C04010",
    "#E05818",
    "#FAD0A8",
    "#502808",
    "cap",
    "normal",
    "#202840",
    null,
  ],
  로사: [
    "#B83870",
    "#D05888",
    "#FAD0A8",
    "#704010",
    "twintails",
    "normal",
    "#704010",
    "hat",
  ],
  마박사: [
    "#6A5840",
    "#F0F0E8",
    "#F0C898",
    "#D0D0D0",
    "top",
    "old",
    "#505060",
    null,
  ],
  주박사: [
    "#204870",
    "#F0F0E8",
    "#FAD0A8",
    "#1A4870",
    "top",
    "normal",
    "#204870",
    null,
  ],
  털보박사: [
    "#5A4030",
    "#F0F0E8",
    "#F0C898",
    "#8B5A20",
    "top",
    "kind",
    "#303030",
    "moustache",
  ],
  지우: [
    "#1A3870",
    "#C83018",
    "#FAD0A8",
    "#181818",
    "cap",
    "det",
    "#1A3870",
    null,
  ],
};

// ── 팀 배틀 ──
export const TEAM_A_COLOR = "#3B82F6";
export const TEAM_B_COLOR = "#EF4444";

// ── CSS 애니메이션 ──
export const GAME_STYLES = `
  @keyframes handPulse        { 0%,100%{box-shadow:0 0 0 3px #4ADE80,0 0 28px 8px rgba(74,222,128,0.4)}  50%{box-shadow:0 0 0 5px #4ADE80,0 0 48px 16px rgba(74,222,128,0.65)} }
  @keyframes teamAPulse       { 0%,100%{box-shadow:0 0 0 3px #3B82F6,0 0 28px 8px rgba(59,130,246,0.4)}  50%{box-shadow:0 0 0 5px #3B82F6,0 0 48px 16px rgba(59,130,246,0.65)} }
  @keyframes teamBPulse       { 0%,100%{box-shadow:0 0 0 3px #EF4444,0 0 28px 8px rgba(239,68,68,0.4)}   50%{box-shadow:0 0 0 5px #EF4444,0 0 48px 16px rgba(239,68,68,0.65)}  }
  @keyframes popIn            { 0%{transform:scale(0.7);opacity:0} 100%{transform:scale(1);opacity:1} }
  @keyframes cardSlideIn      { 0%{opacity:0;transform:translateY(-22px) scale(0.85)} 100%{opacity:1;transform:translateY(0) scale(1)} }
  @keyframes thinkFloat       { 0%,100%{transform:translateX(-50%) translateY(0)} 50%{transform:translateX(-50%) translateY(-3px)} }
  @keyframes dealStagger      { 0%{opacity:0;transform:translateY(14px) scale(0.92)} 100%{opacity:1;transform:translateY(0) scale(1)} }
  @keyframes sdBtnPulse       { 0%,100%{box-shadow:0 0 10px rgba(239,68,68,0.5)} 50%{box-shadow:0 0 28px rgba(239,68,68,0.9)} }
  @keyframes sdFlash          { 0%,100%{opacity:0} 20%,50%{opacity:0.2} 80%{opacity:0} }
  @keyframes sdReveal         { 0%{opacity:0;transform:translate(-50%,-50%) scale(0.2)} 25%{opacity:1;transform:translate(-50%,-50%) scale(1.15)} 55%{transform:translate(-50%,-50%) scale(1);opacity:1} 85%{opacity:1} 100%{opacity:0} }
  @keyframes discardBtnPulse  { 0%,100%{box-shadow:0 4px 16px rgba(239,68,68,0.5)} 50%{box-shadow:0 4px 24px rgba(239,68,68,0.8)} }
  @keyframes emoteFloat       { 0%{opacity:0;transform:translateX(-50%) scale(0.3) translateY(20px)} 15%{opacity:1;transform:translateX(-50%) scale(1.15) translateY(-6px)} 80%{opacity:1} 100%{opacity:0;transform:translateX(-50%) scale(0.9) translateY(-20px)} }
  @keyframes setGlow          { 0%,100%{box-shadow:0 0 10px rgba(251,191,36,0.6);opacity:0.85} 50%{box-shadow:0 0 22px rgba(251,191,36,1);opacity:1} }
  @keyframes particleBurst    { 0%{transform:translate(-50%,-50%) translate(0,0) scale(1);opacity:1} 100%{transform:translate(-50%,-50%) translate(var(--dx),var(--dy)) scale(0);opacity:0} }
  @keyframes spin             { to{transform:rotate(360deg)} }
`;
