// src/lib/sealTypes.js 로 저장하세요
// ── 1세대 포켓몬 타입 (pokeId 기준) ──────────────────────
// 타입이 2개인 경우 대표 타입(첫 번째) 기준
export const SEAL_TYPES = {
  1: "grass", // 이상해씨
  2: "grass", // 이상해풀
  3: "grass", // 이상해꽃
  4: "fire", // 파이리
  5: "fire", // 리자드
  6: "fire", // 리자몽
  7: "water", // 꼬부기
  8: "water", // 어니부기
  9: "water", // 거북왕
  10: "bug", // 캐터피
  11: "bug", // 단데기
  12: "bug", // 버터플
  13: "bug", // 뿔충이
  14: "bug", // 딱충이
  15: "bug", // 독침붕
  16: "normal", // 구구
  17: "normal", // 피죤
  18: "normal", // 피죤투
  19: "normal", // 꼬렛
  20: "normal", // 레트라
  21: "normal", // 깨비참
  22: "normal", // 깨비드릴조
  23: "poison", // 아보
  24: "poison", // 아보크
  25: "electric", // 피카츄
  26: "electric", // 라이츄
  27: "ground", // 모래두지
  28: "ground", // 고지
  29: "poison", // 니드런♀
  30: "poison", // 니드리나
  31: "poison", // 니드퀸
  32: "poison", // 니드런♂
  33: "poison", // 니드리노
  34: "poison", // 니드킹
  35: "normal", // 삐삐
  36: "normal", // 픽시
  37: "fire", // 식스테일
  38: "fire", // 나인테일
  39: "normal", // 푸린
  40: "normal", // 푸크린
  41: "poison", // 주뱃
  42: "poison", // 골뱃
  43: "grass", // 뚜벅쵸
  44: "grass", // 냄새꼬
  45: "grass", // 라플레시아
  46: "bug", // 파라스
  47: "bug", // 파라섹트
  48: "bug", // 콘팡
  49: "bug", // 도나리
  50: "ground", // 디그다
  51: "ground", // 닥트리오
  52: "normal", // 나옹
  53: "normal", // 페르시온
  54: "water", // 고라파덕
  55: "water", // 골덕
  56: "fighting", // 망키
  57: "fighting", // 성원숭
  58: "fire", // 가디
  59: "fire", // 윈디
  60: "water", // 발챙이
  61: "water", // 슈륙챙이
  62: "water", // 강챙이
  63: "psychic", // 캐이시
  64: "psychic", // 윤겔라
  65: "psychic", // 후딘
  66: "fighting", // 알통몬
  67: "fighting", // 근육몬
  68: "fighting", // 괴력몬
  69: "grass", // 모다피
  70: "grass", // 우츠동
  71: "grass", // 우츠보트
  72: "water", // 왕눈해
  73: "water", // 독파리
  74: "rock", // 꼬마돌
  75: "rock", // 데구리
  76: "rock", // 딱구리
  77: "fire", // 포니타
  78: "fire", // 날쌩마
  79: "water", // 야돈
  80: "water", // 야도란
  81: "electric", // 코일
  82: "electric", // 레어코일
  83: "normal", // 파오리
  84: "normal", // 두두
  85: "normal", // 두트리오
  86: "water", // 쥬쥬
  87: "water", // 쥬레곤
  88: "poison", // 질퍽이
  89: "poison", // 질뻐기
  90: "water", // 셀러
  91: "water", // 파르셀
  92: "ghost", // 고오스
  93: "ghost", // 고우스트
  94: "ghost", // 팬텀
  95: "rock", // 롱스톤
  96: "psychic", // 슬리프
  97: "psychic", // 슬리퍼
  98: "water", // 크랩
  99: "water", // 킹크랩
  100: "electric", // 찌리리공
  101: "electric", // 붐볼
  102: "grass", // 아라리
  103: "grass", // 나시
  104: "ground", // 탕구리
  105: "ground", // 텅구리
  106: "fighting", // 시라소몬
  107: "fighting", // 홍수몬
  108: "normal", // 내루미
  109: "poison", // 또가스
  110: "poison", // 또도가스
  111: "ground", // 뿔카노
  112: "ground", // 코뿌리
  113: "normal", // 럭키
  114: "grass", // 덩쿠리
  115: "normal", // 캥카
  116: "water", // 쏘드라
  117: "water", // 시드라
  118: "water", // 콘치
  119: "water", // 왕콘치
  120: "water", // 별가사리
  121: "water", // 아쿠스타
  122: "psychic", // 마임맨
  123: "bug", // 스라크
  124: "ice", // 루주라
  125: "electric", // 에레브
  126: "fire", // 마그마
  127: "bug", // 쁘사이저
  128: "normal", // 켄타로스
  129: "water", // 잉어킹
  130: "water", // 갸라도스
  131: "water", // 라프라스
  132: "normal", // 메타몽
  133: "normal", // 이브이
  134: "water", // 샤미드
  135: "electric", // 쥬피썬더
  136: "fire", // 부스터
  137: "normal", // 폴리곤
  138: "rock", // 암나이트
  139: "rock", // 암스타
  140: "rock", // 투구
  141: "rock", // 투구푸
  142: "rock", // 프테라
  143: "normal", // 잠만보
  144: "ice", // 프리져
  145: "electric", // 썬더
  146: "fire", // 파이어
  147: "dragon", // 미뇽
  148: "dragon", // 신뇽
  149: "dragon", // 망나뇽
  150: "psychic", // 뮤츠
  151: "psychic", // 뮤
};

// ── 타입별 씰 목록 헬퍼 ──────────────────────────────────
export function getSealsByType(seals, type) {
  return seals.filter((s) => SEAL_TYPES[s.pokeId] === type);
}

// ── 특정 타입 수집 개수 헬퍼 ────────────────────────────
export function countCollectedByType(seals, dex, type) {
  return getSealsByType(seals, type).filter((s) => dex[String(s.id)]?.count > 0)
    .length;
}
